Repository nextcloud/files_texteditor, pull requests merged in 2020-10, with the labels that each got.

#125 Default to preview mode when the editor is readonly
  js/editor.js
Labels: 4. to release, enhancement

#239 added a website-url...
  appinfo/info.xml
Labels: 4. to release

#286 use fetch for network requests
  Makefile
  js/editor.js
  package-lock.json
  package.json
Labels: 3. to review

#281 Prepare release of 2.12.0
  CHANGELOG.md
Labels: 2. developing
